_wandb:
    value:
        cli_version: 0.25.0
        e:
            waehyvyxs8tw1p7riywd4ydx5b0ef1li:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "2147483648"
                codePath: src/training.py
                codePathLocal: src/training.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "144106614784"
                email: chrishalkiaskali@gmail.com
                executable: /Users/chrischalkias/GitHub/QRN-RL-GNN/.venv/bin/python
                git:
                    commit: 35e11a99e7f98ff193e712027257db5ea2be8779
                    remote: https://github.com/chrishalkias/QRN-RL-GNN
                host: Chriss-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-15.7.3-arm64-arm-64bit-Mach-O
                program: /Users/chrischalkias/GitHub/QRN-RL-GNN/src/training.py
                python: CPython 3.13.2
                root: /Users/chrischalkias/GitHub/QRN-RL-GNN
                startedAt: "2026-02-16T16:54:24.892729Z"
                writerId: waehyvyxs8tw1p7riywd4ydx5b0ef1li
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 1
                - 16
                - 41
            "4": 3.13.2
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
batch_size:
    value: 128
cutoff:
    value: 300
episodes:
    value: 5000
fine_tune:
    value: false
gamma:
    value: 0.95
lr:
    value: 0.0005
n_nodes_range:
    value:
        - 4
p_entangle:
    value: 0.85
p_swap:
    value: 0.95
tau:
    value: 500
